### ISSUE TITLE
Remaining backend issues

### ISSUE THREAD

**Issue by psdcode** [ajah/sks-interface#65]
Just creating a master issue for all of the remaining backend based issues/features that are related to the recent front-end upgrades. If some of these are already implemented since the last time I checked feel free to check them off

- [ ]  the `doctype` parameter still accepts keyword `entity`, instead of accepting `organization` instead (or in addition to `entity` , and return same result). See issue https://github.com/ajah/sks-interface/issues/56
- [ ]  AND/OR parsing for cities and regions. AND within a term (eg New AND York), and OR between cities/regions. See issue https://github.com/ajah/sks-interface/issues/55
- [ ] the backend parsing of specific inclusion and exclusion lists (to be provided by Gustavo) for the new search filter terms, currently passed in the `terms` param. See issue https://github.com/ajah/sks-interface/issues/60
- [ ] when doctype is activities, multiple types of data (different `_index` values) but with duplicate `_id` properties are passed. Please filter out duplicate data and keep only one type of `_index` values, unless I misunderstood this. See issue https://github.com/ajah/sks-server/issues/10
- [ ] `/count` endpoint not accepting the same query params as `/search`. See issue https://github.com/ajah/sks-interface/issues/54

DONE
- [x] backend accepts now accepts `city` param instead of `municipality`
